version: "3.7"

services:
  czkawka:
    image: jlesage/czkawka
    hostname: czkawka-container
    ports:
      - "5800:5800"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "config:/config:rw"
      - "medialibrary_share:/storage:ro"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
      
volumes:
  config:
  medialibrary_share:
    driver_opts:
      type: "cifs"
      o: "username=${SHARE_CIFS_USER?Environment variable SHARE_CIFS_USER is not set},password=${SHARE_CIFS_PASSWORD?Environment variable SHARE_CIFS_PASSWORD is not set},vers=3.0,ro,uid=${CTNUSER_OUTER_UID?Environment variable CTNUSER_OUTER_UID is not set},gid=${CTNUSER_OUTER_GID?Environment variable CTNUSER_OUTER_GID is not set}"
      device: "${MEDIALIBRARY_SHARE_CIFS_URI}"
