version: "3.7"

services:
  mldonkey:
    image: logicwar/mldonkey
    hostname: mldonkey-container
    environment:
      - PUID=${CTNUSER_INNER_UID}
      - PGID=${CTNUSER_INNER_GID}
    ports:
      - "4080:4080"
      - "20562:20562"
      - "20566:20566/udp"
      - "16965:16965"
      - "16965:16965/udp"
      - "6209:6209"
      - "6209:6209/udp"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "mldonkey_config:/var/lib/mldonkey:rw"
      - "mldonkey_tmp_dl:/mnt/mldonkey_tmp:rw"
      - "mldonkey_network_share:/mnt/mldonkey_completed:rw"
    # cap_drop:
      # - ALL
    # cap_add:
      # - CHOWN
      # - SETUID
      # - SETGID
      # - FOWNER
      # - DAC_OVERRIDE
      
volumes:
  mldonkey_config:
  mldonkey_tmp_dl:
  mldonkey_network_share:
    driver_opts:
      type: "cifs"
      o: "username=mldonkey,password=${SHARE_CIFS_PASSWORD?Environment variable SHARE_CIFS_PASSWORD is not set},vers=3.0,uid=${CTNUSER_OUTER_UID?Environment variable CTNUSER_OUTER_UID is not set},gid=${CTNUSER_OUTER_GID?Environment variable CTNUSER_OUTER_GID is not set}"
      device: "${SHARE_CIFS_URI}"